### ISSUE TITLE
System.InvalidCastException: 'Unable to cast object of type 'System.Collections.Generic.Dictionary

### ISSUE THREAD

**Issue by luanmacek** [fysh711426/UndetectedChromeDriver#15]
Hello when I try to use library I get this error whenever code goes on line calling method driver.GoToUrl(). It happens in example project too

![image](https://user-images.githubusercontent.com/43366123/178217180-3ca80531-9bd1-41d2-861c-3b526f73b696.png)

**Comment by fysh711426** [comment]
Is there any initialization code with `UndetectedChromeDriver.Create`?

**Comment by luanmacek** [comment]
string path = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "ChromeDriver/chromedriver.exe");
var options = new ChromeOptions();
options.AddArgument("--mute-audio");
options.AddArgument("--disable-gpu");
options.AddArgument("--disable-dev-shm-usage");
using var driver = UndetectedChromeDriver.Create(options: options,driverExecutablePath: path);

**Comment by fysh711426** [comment]
Selenium version is? 
This is a confusing error.

**Comment by luanmacek** [comment]
Chrome version **103.0.5060.114** and Selenium.UndetectedChromeDriver **1.06**

**Comment by luanmacek** [comment]
Fixed it by downgrading chrome and chromedriver to version 75.0.3770.80
