### ISSUE TITLE
Working with many browsers

### ISSUE THREAD

**Issue by mgawrysiak** [fysh711426/UndetectedChromeDriver#2]
Hi, in first place grate job with this!

I hope u can help me with my problem, I have code from 2 days ago. I implemented your solution into wpf app. The idea is to have many instances of that app. Each instance have its own folder with own userDataPath (I need to save some data there)

For first 2 instances it works fine, but when I try to run 3rd instance it's opening browser with some url like folder/BrowserProfile or copy/BrowserProfile or 0.0.0.2/BrowserProfile, once it opened with 2 tabs, first has url '-' and second copy/BrowserProfile. 

I'm setting browser profile path like that:

var userDataPath = $"{AppDomain.CurrentDomain.BaseDirectory}BrowserProfile";

Maybe u can help me with that?

**Comment by fysh711426** [comment]
Thanks for your question,
Opening multiple instances will cause conflicts.
I will study the reason.

**Comment by fysh711426** [comment]
Are your options shared?
This code will add something to the options,
I found a problem with sharing, try using separate options for each instance.

**Comment by mgawrysiak** [comment]
I think you don't understand me, in my case it is one wpf application, inside this wpf application there is one instance of undetected chromedriver. Then I run this application (app.exe) from 3 folders:

- App1 folder (path C: \ Apps \ App1)
     - BrowserProfile folder (C: \ Apps \ App1 \ BrowserProfile)
     -app.exe
- App2 folder (path C: \ Apps \ App2)
     - BrowserProfile folder (C: \ Apps \ App2 \ BrowserProfile)
     -app.exe
- App3 folder (path C: \ Apps \ App3)
     - BrowserProfile folder (C: \ Apps \ App3 \ BrowserProfile)
     -app.exe
 
I also noticed that when I run app.exe from the App3 folder, it opens a browser with the address 'copy/BrowserProfile' (on other computers it's 'folder/BrowserProfile' or '0.0.0.2/BrowserProfile' folder) and creates browser profile files in the App 1 folder

**Comment by fysh711426** [comment]
I can not understand this  

> it opens a browser with the address 'copy/BrowserProfile' (on other computers it's 'folder/BrowserProfile' or '0.0.0.2/BrowserProfile' folder) and creates browser profile files in the App 1 folder  

Maybe I need some screenshots.

**Comment by mgawrysiak** [comment]
![image](https://user-images.githubusercontent.com/37868249/169713348-b018c158-b7a1-43cb-84f4-cdd8cd8f482a.png)
![image](https://user-images.githubusercontent.com/37868249/169713366-92e6621b-601d-4a4c-8be6-b2c87053b9df.png)
![image](https://user-images.githubusercontent.com/37868249/169713304-04773d57-1df4-427f-adab-ade5f6f6f6b6.png)

**Comment by mgawrysiak** [comment]
Above screenshots are from scenario when I run app.exe from App3 folder

**Comment by fysh711426** [comment]
Thanks, is there a problem with the url of GoToUrl(url)?
I suggest you can take a look at Console.Write.

**Comment by mgawrysiak** [comment]
There is no GoToUrl yet, it is just initialization of browser (GoToUrl will trigger when I click button on wpf app)

**Comment by fysh711426** [comment]
Sorry I can't reproduce, I tested with Console and everything works fine. 

```C#
public static void Test()
{
    var driverExecutablePath = $@"D:\xxx\chromedriver.exe";

    var userDataDir = 
        $"{AppDomain.CurrentDomain.BaseDirectory}BrowserProfile";

    using var driver = UndetectedChromeDriver.Create(
        options: new ChromeOptions(),
        driverExecutablePath: driverExecutablePath,
        userDataDir: userDataDir);

    Console.ReadLine();
}
```
![1653296735688](https://user-images.githubusercontent.com/31367880/169784626-36553439-8ceb-4c95-84c9-398208351ad8.jpg)  

![1653296695025](https://user-images.githubusercontent.com/31367880/169784651-3e76296f-aee7-4842-9853-94df577c7525.jpg)  

![1653296247016](https://user-images.githubusercontent.com/31367880/169783822-6792420f-70b9-4b8d-9121-308d692ecbca.jpg)

**Comment by mgawrysiak** [comment]
Ok, I will prepare some demo, and will add it to my repo.

**Comment by fysh711426** [comment]
I think that the code mainly uses options.Arguments to start the chrome Process. 
Do you use suspicious parameters in your options ? 

```C#
var info = new ProcessStartInfo(options.BinaryLocation,
    string.Join(" ", options.Arguments));
```

**Comment by mgawrysiak** [comment]
The problem was that there cannot be any spaces in userDataDir. The folder tree that I sent you before was just mockup, and in real data there was something like "C:\App - Copy\" and "C:\App1\", "C:\App2\" "C:\App 3\"

**Comment by fysh711426** [comment]
Ok, I fixed it. thanks!
