### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by Bagietta** [fysh711426/UndetectedChromeDriver#21]
Hey,
How can I disable this debug log?

Starting ChromeDriver 106.0.5249.61 (511755355844955cd3e264779baf0dd38212a4d0-refs/branch-heads/5249@{#569}) on port 52835
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

**Comment by fysh711426** [comment]
I released a alpha package, you can try it.  

```
PM> Install-Package Selenium.UndetectedChromeDriver -Version 1.0.7-alpha
```

`SuppressInitialDiagnosticInformation` can disable debug log.

```C#
using var driver = UndetectedChromeDriver.Create(
    ...
    configureService: (service) =>
    {
        // Suppress initial chrome driver information.
        service.SuppressInitialDiagnosticInformation = true;
    });
```
