### ISSUE TITLE
How to use proxies with authentication?

### ISSUE THREAD

**Issue by devWade** [fysh711426/UndetectedChromeDriver#30]
Can't figure out how to fill in username and password for paid proxies.

**Comment by fysh711426** [comment]
Maybe it can be solved by using the extension.

```C#
var extension = @"D:\ChromeExtensions\Extension";
options.AddArgument($"--load-extension={extension1}");
```

> With "load-extension", only unpackaged (folder) plugins can be loaded, crx files are not supported.

**Comment by devWade** [comment]
Worked cheers

**Comment by senzacionale** [comment]
Can you give an example with extensions please?
