### ISSUE TITLE
Patcher corrupts chromedriver binary on MacOS (M1)

### ISSUE THREAD

**Issue by Radu-D** [fysh711426/UndetectedChromeDriver#40]
Diff between original and patched driver:
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/28422412/222831729-a85e1dff-3524-4b99-9f80-d4fe328b916b.png">
----
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/28422412/222831783-9df37404-6e4c-4d43-b781-716b93803115.png">

Error:
`OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://127.0.0.1:37427/`
\
[Patcher](https://github.com/fysh711426/UndetectedChromeDriver/blob/master/UndetectedChromeDriver/Patcher.cs#L9)

- V110.0.5481 ARM64
- UndetectedDriver works fine on Windows 10 with sample code
- If I don't patch/alter the driver file, Chrome and chromedriver start without problems (but can't pass CloudFlare protection)

Thanks in advance!

----
**Edit:
I found that using `Encoding.Unicode` instead of `Encoding.GetEncoding("ISO-8859-1")` solves it!**

**Comment by JvB94** [comment]
PR: https://github.com/fysh711426/UndetectedChromeDriver/pull/41

**Comment by fysh711426** [comment]
I'm not sure if Encoding.Unicode will break the binary.

**Comment by Radu-D** [comment]
> Can x64 chromedriver run on MacOS (M1) ? I don't have a mac test environment.

It apparently can.
#41 fixes it on M1! Good stuff 👍

Proof:
<img width="2093" alt="image" src="https://user-images.githubusercontent.com/28422412/223762297-7771f315-229f-4ffe-9db5-12be16d15279.png">

**Comment by Radu-D** [comment]
Closing. Fix has been merged with #41.
