### ISSUE TITLE
Question: where is this function "ExecuteCdpCommand" defined. 

### ISSUE THREAD

**Issue by devCanario** [fysh711426/UndetectedChromeDriver#66]
i cant find anything about this function but i want to use it in my code.
https://github.com/fysh711426/UndetectedChromeDriver/blob/8b9deef7820b3fb04f408faaae12d5684a0eebbc/UndetectedChromeDriver/UndetectedChromeDriver.cs#L255C18-L255C19

**Comment by fysh711426** [comment]
You are right.
